from encodings import utf_8
coding:utf_8

from xml.dom.minidom import Document

doc = Document()

root = doc.createElement('content')

rxGain = doc.createElement('rxGain')
txPwr = doc.createElement('txPwr')
cell = doc.createElement('cell')

item = doc.createElement('item')
arfcnList = doc.createElement('arfcnList')
arfcn= doc.createElement('arfcn')
mcc = doc.createElement('mcc')
mnc = doc.createElement('mnc')
lai = doc.createElement('lai')
sib3CellId = doc.createElement('sib3CellId')
bsic = doc.createElement('bsic')
cro = doc.createElement('cro')
rxLevAccMin = doc.createElement('rxLevAccMin')
reselctHyst = doc.createElement('reselctHyst')
nbFreq = doc.createElement('nbFreq')

#atributos das tags
cell.setAttribute('itemCnt','2')
arfcn.setAttribute('itemCnt','1')

#Iniciação da árvore
doc.appendChild(root)
root.appendChild(rxGain)
root.appendChild(txPwr)
root.appendChild(cell)
cell.appendChild(item)
item.appendChild(arfcnList)
arfcnList.appendChild(arfcn)
item.appendChild(mcc)
item.appendChild(mnc)
item.appendChild(lai)
item.appendChild(sib3CellId)
item.appendChild(bsic)
item.appendChild(cro)
item.appendChild(rxLevAccMin)
item.appendChild(reselctHyst)
item.appendChild(nbFreq)

#inserindo dados 
txt0 = doc.createTextNode('50')
rxGain.appendChild(txt0)
txt1 = doc.createTextNode('45')
txPwr.appendChild(txt1)
txt2 = doc.createTextNode('623')
arfcn.appendChild(txt2)
txt3 = doc.createTextNode('724')
mcc.appendChild(txt3)
txt4 = doc.createTextNode('10')
mnc.appendChild(txt4)
txt5 = doc.createTextNode('2210')
lai.appendChild(txt5)
txt6 = doc.createTextNode('5421')
sib3CellId.appendChild(txt6)
txt7 = doc.createTextNode('41')
bsic.appendChild(txt7)
txt8 = doc.createTextNode('60')
cro.appendChild(txt8)
txt9 = doc.createTextNode('0')
rxLevAccMin.appendChild(txt9)
txt10 = doc.createTextNode('0')
reselctHyst.appendChild(txt10)
txt11 = doc.createTextNode('178')
nbFreq.appendChild(txt11)

item = doc.createElement('item')
arfcnList = doc.createElement('arfcnList')
arfcn= doc.createElement('arfcn')
mcc = doc.createElement('mcc')
mnc = doc.createElement('mnc')
lai = doc.createElement('lai')
sib3CellId = doc.createElement('sib3CellId')
bsic = doc.createElement('bsic')
cro = doc.createElement('cro')
rxLevAccMin = doc.createElement('rxLevAccMin')
reselctHyst = doc.createElement('reselctHyst')
nbFreq = doc.createElement('nbFreq')

cell.appendChild(item)
item.appendChild(arfcnList)
arfcnList.appendChild(arfcn)
item.appendChild(mcc)
item.appendChild(mnc)
item.appendChild(lai)
item.appendChild(sib3CellId)
item.appendChild(bsic)
item.appendChild(cro)
item.appendChild(rxLevAccMin)
item.appendChild(reselctHyst)
item.appendChild(nbFreq)

#inserindo dados 
txt2 = doc.createTextNode('631')
arfcn.appendChild(txt2)
txt3 = doc.createTextNode('724')
mcc.appendChild(txt3)
txt4 = doc.createTextNode('05')
mnc.appendChild(txt4)
txt5 = doc.createTextNode('1211')
lai.appendChild(txt5)
txt6 = doc.createTextNode('5421')
sib3CellId.appendChild(txt6)
txt7 = doc.createTextNode('32')
bsic.appendChild(txt7)
txt8 = doc.createTextNode('60')
cro.appendChild(txt8)
txt9 = doc.createTextNode('0')
rxLevAccMin.appendChild(txt9)
txt10 = doc.createTextNode('0')
reselctHyst.appendChild(txt10)
txt11 = doc.createTextNode('836')
nbFreq.appendChild(txt11)

doc.writexml( open('clone.xml', 'w'),
             addindent='  ',
             newl='\n' )


doc.unlink()    